source 'http://rubygems.org'
gem 'json', '~> 1.7.7'
gem 'pg'
gem 'goliath'
gem 'grape'
gem 'em-synchrony'
gem 'rgeo'
gem 'rgeo-geojson'
gem 'rgeo-activerecord', '= 0.5.0'
gem 'activerecord-postgis-adapter', '= 0.6.4'
